### ISSUE TITLE
1.18 - Mip level 0

### ISSUE THREAD

**Issue by itsdinkd** [GmsGarcia/compress-em#1]
Please fix texture

[18:34:33] [Worker-Main-8/WARN]: Texture compress:item/bag_with_lily_of_the_valley with size 16x17 limits mip level from 4 to 0

**Comment by GmsGarcia** [comment]
Hi **red2blue**! That's just a warning about the texture's resolution and I'll fix it in the future. But this warning/error doesn't compromise your gameplay with the any mod, including **Compress 'Em**.

**Comment by itsdinkd** [comment]
It actually does compromise the gameplay. It reduces mipmap levels to 0 meaning Textures look worse. 
`[21:16:01] [Server-Worker-7/WARN]: minecraft:textures/atlas/blocks.png: dropping miplevel from 4 to 0, because of minimum power of two: 1`
